services:
  inventory-management-system-api:
    container_name: inventory_management_system_api_container
    build: .
    volumes:
      - ./inventory_management_system_api:/inventory-management-system-api-run/inventory_management_system_api
      - ./keys:/inventory-management-system-api-run/keys
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - mongo-db
    network_mode: "host"

  mongo-db:
    image: mongo:7.0-jammy
    container_name: ims_api_mongodb_container
    command: ["--replSet", "rs0", "--keyFile", "/etc/mongodb/keys/rs_keyfile"]
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/keys:/etc/mongodb/keys
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    network_mode: "host"
